steps:

# CLOUD BUILD SERVICE ACCOUNT IAM ROLES

- id: "terraform init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/cloudbuild-sde'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/cloudbuild-sde'
  ]

- id: "terraform plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/cloudbuild-sde'
  args: [
    'plan'
  ]

- id: "terraform apply"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/cloudbuild-sde'
  args: [
    'apply',
    '-auto-approve'
  ]

timeout: 1800s