steps:

# CLOUD BUILD SERVICE ACCOUNT IAM ROLES

- id: "terraform init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/cloudbuild-sde'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/cloudbuild-sde'
  ]

- id: "terraform plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/cloudbuild-sde'
  args: [
    'plan',
    '-destroy'
  ]

- id: "terraform destroy"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/cloudbuild-sde'
  args: [
    'destroy',
    '-auto-approve'
  ]

timeout: 1800s