steps:

# CLOUD COMPOSER WITH DAGS

- id: "composer init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/staging-project/cloud-composer'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/cloud-composer'
  ]

- id: "composer plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/staging-project/cloud-composer'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-var=terraform_foundation_state_prefix=${_PREFIX}'
  ]