timeout: 3600s

steps:

# SECURE DATA STAGING PROJECT

- id: "data-ops projects - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops-project'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/data-ops-project'
  ]

  
- id: "data-ops project - destroy plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops-project'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-destroy'
  ]

- id: "data-ops project - destroy all"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops-project'
  args: [
  'destroy',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-auto-approve'
  ]
