timeout: 1800s

steps:
# BUILD THE IMAGE AND TAGGING IT
- id: build container
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest', '-f', './containers/pre-commit/Dockerfile', '.']

# PUSH THE CONTAINER IMAGE INTO THE ARTIFACT REGISTRY
# Tag using the SHA from the trigger
- id: push SHA container
  name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA']

# Tag using `latest`
- id: push latest container
  name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest']

images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA','gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest']