# The below steps are if a manual `gcloud build submit` job needs to be run from the `packer-container` directory.
# $ gcloud builds submit . --config=packer-main-cloudbuild.yaml
# IAM Roles - Service Usage Admin, Storage Admin, and Cloud Build Editor at the Packer project level.
# If Resource Location Restriction error occurs create a GCS bucket in packer project as <PROJECT-ID_cloudbuild>
# Create Artifact Registry called "packer"

# See docs at https://www.packer.io/docs/install/index.html

# TODO: Create a Cloud Build pipeline in cloudbuild-iam-and-pipelines/main.tf

timeout: 1800s

steps:
  - name: 'gcr.io/cloud-builders/wget'
    dir: 'environment/foundation/packer-project/packer-container'
    args: ["https://releases.hashicorp.com/packer/${_PACKER_VERSION}/packer_${_PACKER_VERSION}_linux_amd64.zip"]

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'environment/foundation/packer-project/packer-container'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${_PACKER_PROJECT_ID}/packer/packer:latest',
          '-t', '${_REGION}-docker.pkg.dev/${_PACKER_PROJECT_ID}/packer/packer:${_PACKER_VERSION}',
           '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
           '--build-arg', 'PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}',
           '.']

substitutions:
  _PACKER_VERSION: 1.7.3
  _PACKER_VERSION_SHA256SUM: 1a8719f0797e9e45abd98d2eb38099b09e5566ec212453052d2f21facc990c73

images:
  - '${_REGION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/packer/packer:latest'
  - '${_REGION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/packer/packer:${_PACKER_VERSION}'
tags: ['cloud-builders-community']
