steps:

# PACKER PROJECT

- id: "terraform init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image-project'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/image-project'
  ]

- id: "terraform plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image-project'
  args: [
    'plan',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
  ]

timeout: 3600s