steps:

# PACKER PROJECT

- id: "terraform init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/packer-project'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/packer-project'
  ]

- id: "terraform plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/packer-project'
  args: [
    'plan'
  ]

timeout: 3600s