timeout: 1800s

steps:

steps:
- name: ubuntu 
  id: 'create_image_spec'
  entrypoint: "bash"
  args:
    - '-c'
    - |
      cat <<END>packer.json
      {
      "variables": {
        "working_dir": "/opt",
        "src_folder": "src_files"
      },
      "builders": [
        {
          "type": "googlecompute",
          "instance_name": "packer-builder-vm-$SHORT_SHA",
          "disk_size": "50",
          "project_id": "${_PACKER_PROJECT_ID}",
          "source_image_family": "${_IMAGE_FAMILY}",
          "image_name": "custom-image-$SHORT_SHA",
          "image_family": "packer-custom-image",
          "image_description": "created-with-packer",
          "communicator": "ssh",
          "ssh_username": "ubuntu",
          "subnetwork" : "projects/${_PACKER_PROJECT_ID}/regions/${_REGION}/subnetworks/packer-us-central1-subnet",
          "zone": "${_IMAGE_ZONE}",
          "tags": ["packer"],
          "use_os_login":true,
          "enable_secure_boot": true,
          "enable_vtpm": true,
          "enable_integrity_monitoring": true,          
          "scopes": [
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/compute",
            "https://www.googleapis.com/auth/devstorage.full_control",
            "https://www.googleapis.com/auth/logging.admin"
          ]
        }
        ],
      "provisioners": [
        {
          "type": "shell",
          "inline": [
            "sudo apt-get update -qq",
            "sudo apt-get upgrade -qq"
          ]
        }
      ]
      }
      END

- id: 'VM Build and Image Creation'
  name: '${_REGION}-docker.pkg.dev/${_PACKER_PROJECT_ID}/packer/packer:${_PACKER_IMAGE_TAG}'
  args:
    - build
    - -var
    - project_id=${_PACKER_PROJECT_ID}
    - packer.json