timeout: 1800s

steps:

- id: "image project state pull - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image-project'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/image-project'
  ]

- id: output file creation - image project
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image-project'
  entrypoint: /bin/sh
  args: [
    '-c',
    #'terraform output subnets_names[0] > /workspace/subnets_names.txt',
    'terraform output project_id > /workspace/project_id.txt'
  ]

- name: ubuntu 
  id: 'create_image_spec'
  entrypoint: "bash"
  args:
    - '-c'
    - |
      cat <<END>packer.json
      {
      "variables": {
        "working_dir": "/opt",
        "src_folder": "src_files"
      },
      "builders": [
        {
          "type": "googlecompute",
          "instance_name": "packer-builder-vm-$SHORT_SHA",
          "disk_size": "50",
          "project_id": "$(cat /workspace/project_id.txt)",
          "source_image_family": "${_IMAGE_FAMILY}",
          "image_name": "custom-image-$SHORT_SHA",
          "image_family": "packer-custom-image",
          "image_description": "created-with-packer",
          "communicator": "ssh",
          "ssh_username": "ubuntu",
          "subnetwork" : "projects/$(cat /workspace/project_id.txt)/regions/${_REGION}/subnetworks/image-us-central1-subnet",
          "zone": "${_IMAGE_ZONE}",
          "tags": ["packer"],
          "use_os_login":true,
          "enable_secure_boot": true,
          "enable_vtpm": true,
          "enable_integrity_monitoring": true,          
          "scopes": [
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/compute",
            "https://www.googleapis.com/auth/devstorage.full_control",
            "https://www.googleapis.com/auth/logging.admin"
          ]
        }
        ],
      "provisioners": [
        {
          "type": "shell",
          "inline": [
            "sudo apt-get update -qq",
            "sudo apt-get upgrade -qq"
          ]
        }
      ]
      }
      END

- id: 'VM Build and Image Creation'
  name: '${_REGION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/packer/packer:${_IMAGE_TAG}'
  args:
    - build
    - -var
    - project_id=${_IMAGE_PROJECT_ID}
    - packer.json