steps:


# SCP Workflows

- id: "scp init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/${_PREFIX}/vpc-service-controls/perimeter'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/scp_test'
  ]

- id: "scp plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/vpc-service-controls/perimeter'
  args: [
  'plan'
  ]

- id: "scp apply"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/vpc-service-controls/perimeter'
  args: [
  'apply',
  '-auto-approve'
  ]

timeout: 3600s