steps:


# Service Control Perimeter Terraform Plan Dev

- id: "scp init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/vpc-service-controls/service-perimeter'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/service-perimeter'
  ]

- id: "scp plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/vpc-service-controls/service-perimeter'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars'
  ]

timeout: 3600s