timeout: 3600s

steps:

# SECURE DATA STAGING PROJECT

- id: "staging project - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/staging-project'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/staging-project'
  ]

- id: "staging project - first plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/staging-project'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-target=module.secure-staging-project'
  ]