timeout: 2700s

steps:

# CLOUD COMPOSER

- id: "composer init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/staging-project/cloud-composer'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/cloud-composer'
  ]

- id: "composer plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/staging-project/cloud-composer'
  args: [
  'plan',
  '-destroy'
  ]

- id: "composer destroy"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/staging-project/cloud-composer'
  args: [
  'destroy',
  '-auto-approve'
  ]