timeout: 1800s

steps:


# CLOUD COMPOSER WITH DAGS

- id: "composer init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/staging-project/cloud-composer'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/cloud-composer'
  ]

- id: "composer plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/staging-project/cloud-composer'
  args: [
  'plan'
  ]