timeout: 3600s
steps:
# RESEARCHER PROJECTS WITH DAGS
- id: "researcher projects - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/researcher-projects'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/researcher-projects'
  ]

- id: "researcher projects - plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/researcher-projects'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-destroy'
  ]

- id: "researcher projects - destroy"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/researcher-projects'
  args: [
  'destroy',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-auto-approve'
  ]