steps:

- id: "tf init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects/workspace-1'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform init -backend-config=bucket=${_BUCKET} -backend-config=prefix=${_PREFIX}/$BRANCH_NAME/researcher-projects/${_WORKSPACE}

- id: "terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects/workspace-1'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME


- id: "tf fmt"
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/deployments/researcher-projects/workspace-1'
  args: ['fmt',
    '-check'
    ]

- id: "tf validate"
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/deployments/researcher-projects/workspace-1'
  args: ['validate',
    '-no-color'
    ]

- id: "tf plan - org pol off"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects/workspace-1'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform plan -var=set_disable_sa_create=false -input=false -destroy

- id: "tf destroy - org pol off"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects/workspace-1'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform destroy -var=set_disable_sa_create=false -auto-approve -input=false