steps:

# RESEARCHER PROJECTS WITH DAGS
- id: "researcher projects - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/researcher-projects'
  ]

- id: "researcher projects - plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '--out',
  'tfplan.binary'
  ]

- id: "staging project - first show"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    terraform show -json tfplan.binary > tfplan.json

timeout: 3600s