steps:

# RESEARCHER PROJECTS WITH DAGS
- id: "researcher projects - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/researcher-projects/${_TFVARS_FILE}'
  ]

- id: Terraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/deployments/researcher-projects'
  args: ['fmt',
    '-check'
    ]

- id: Terraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/deployments/researcher-projects'
  args: ['validate',
    '-no-color'
    ]


- id: "researcher projects - plan org policies disabled"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  args: [
    'plan',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
    '-var=terraform_foundation_state_prefix=${_PREFIX_FOUNDATION}',
    '-var=enforce_researcher_workspace_disable_sa_creation=false',
    '-var=enforce_bastion_project_disable_sa_creation=false'
  ]

- id: "researcher projects - apply org policies disabled"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  args: [
    'apply',
    '-auto-approve',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
    '-var=terraform_foundation_state_prefix=${_PREFIX_FOUNDATION}',
    '-var=enforce_researcher_workspace_disable_sa_creation=false',
    '-var=enforce_bastion_project_disable_sa_creation=false'
  ]

- id: "researcher projects - apply org policies enabled"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  args: [
    'apply',
    '-auto-approve',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
    '-var=terraform_foundation_state_prefix=${_PREFIX_FOUNDATION}',
    '-var=enforce_researcher_workspace_disable_sa_creation=true',
    '-var=enforce_bastion_project_disable_sa_creation=true'
  ]


# Create output files to use when performing variable substitution in the Composer DAGs for this workspace
# Changing the workspace paths below will effect the Composer DAG Python scripts

- id: "output file creation - researcher projects"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/researcher-projects'
  entrypoint: /bin/sh
  args: [
    '-c',
    'terraform output -json > /workspace/researcher-output.json && cat /workspace/researcher-output.json'
  ]

- id: "staging project state pull - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/staging-project'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/staging-project'
  ]

- id: "output file creation - staging project"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/staging-project'
  entrypoint: /bin/sh
  args: [
    '-c',
    'terraform output -json > /workspace/staging-output.json && cat /workspace/staging-output.json'
  ]

  # Perform variable substitution in the DAGs and upload all of them to the Composer DAGs folder.

- id: "load variables for Researcher DAG envs"
  name: gcr.io/cloud-builders/gcloud
  dir: 'environment/foundation/staging-project/cloud-composer/composer-dag-files'
  entrypoint: python
  args: [
    'set_researcher_dag_envs.py'
  ]

- id: "load DAG to GCS bucket"
  name: gcr.io/cloud-builders/gsutil
  dir: 'environment/foundation/staging-project/cloud-composer/composer-dag-files'
  args: [
    'cp',
    '-n',
    '/workspace/*_DAG.py',
    'gs://${_COMPOSER_DAG_BUCKET}/dags/'
  ]

timeout: 3600s