steps:


# SRDE FOLDER POLICIES

- id: "srde folder policies init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/srde-folder-policies'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/srde-folder-policies'
  ]

- id: "srde folder policies destroy plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/srde-folder-policies'
  args: [
  'plan',
  '-destroy'
  ]

- id: "srde folder policies destroy apply"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/deployments/wcm-srde/srde-folder-policies'
  args: [
  'destroy',
  '-auto-approve'
  ]

timeout: 1800s